bucket_name:  # Change to the bucket name you want to upload to
root_path:  # Change to the pwd your running this in
folder_starting_word: patagonia_ # This could change, so make sure to change this based on the files given
thread_pool_size: 8
